// Regenerates the favicon/app-icon set from the gold mark
// (public/brand/enactus-mannheim-logo-mark.png) as a round badge: the mark
// centered on a solid ink-navy circle, transparent everywhere outside it.
//
// Two icons deliberately do NOT get that transparent-circle treatment —
// this is a platform constraint, not an inconsistency:
// - apple-icon.png: iOS applies its own squircle mask and can render
//   transparent regions as solid black, so it stays a fully opaque square.
// - icon-maskable-512.png: the maskable spec requires the *entire* canvas
//   to stay opaque (the OS applies its own mask shape on top); only the
//   mark itself needs to sit inside the safe zone, a circle of radius 40%
//   of the icon size centered on the canvas.
//
// Usage: `node scripts/generate-icons.mjs`. No env vars needed — this only
// touches static files in public/ and src/app/, never the database or
// Resend. Not run at build time; committed output, regenerated by hand
// when the source mark changes.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_MARK = join(root, "public/brand/enactus-mannheim-logo-mark.png");
const INK_NAVY = "#061031";

function circleSvg(size, fill) {
  const r = size * 0.48; // small margin so the circle doesn't touch the canvas edge
  const c = size / 2;
  return Buffer.from(`<svg width="${size}" height="${size}"><circle cx="${c}" cy="${c}" r="${r}" fill="${fill}"/></svg>`);
}

// The mark on a transparent canvas, background circle first, mark on top —
// used for every icon whose purpose is "any" (favicon.ico, icon.png,
// icon-192/512.png): transparent outside the circle, navy inside it.
async function roundBadge(size, markScale = 0.6) {
  const circle = await sharp(circleSvg(size, INK_NAVY)).png().toBuffer();
  const markWidth = Math.round(size * markScale);
  const mark = await sharp(SOURCE_MARK).resize({ width: markWidth, fit: "inside" }).toBuffer();
  const markMeta = await sharp(mark).metadata();

  return sharp({ create: { width: size, height: size, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
    .composite([
      { input: circle, top: 0, left: 0 },
      {
        input: mark,
        top: Math.round((size - (markMeta.height ?? size)) / 2),
        left: Math.round((size - (markMeta.width ?? size)) / 2),
      },
    ])
    .png()
    .toBuffer();
}

// A fully opaque square: the mark on a solid navy fill, no circle, no
// transparency anywhere — for apple-icon.png (opaque, own OS mask) and
// icon-maskable-512.png (opaque is required by the maskable spec itself).
async function solidSquare(size, markScale) {
  const markWidth = Math.round(size * markScale);
  const mark = await sharp(SOURCE_MARK).resize({ width: markWidth, fit: "inside" }).toBuffer();
  const markMeta = await sharp(mark).metadata();

  return sharp({ create: { width: size, height: size, channels: 4, background: INK_NAVY } })
    .composite([
      {
        input: mark,
        top: Math.round((size - (markMeta.height ?? size)) / 2),
        left: Math.round((size - (markMeta.width ?? size)) / 2),
      },
    ])
    .png()
    .toBuffer();
}

// Minimal ICO container: a handful of PNG-format entries, which every
// browser and OS this project targets accepts (no legacy BMP encoding
// needed). ICONDIR (6 bytes) + one ICONDIRENTRY (16 bytes) per image,
// followed by the raw PNG bytes themselves.
function packIco(pngBuffers) {
  const count = pngBuffers.length;
  const headerSize = 6 + 16 * count;
  let offset = headerSize;
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(count, 4);

  const entries = [];
  for (const { size, buffer } of pngBuffers) {
    const entry = Buffer.alloc(16);
    entry.writeUInt8(size >= 256 ? 0 : size, 0); // width, 0 means 256
    entry.writeUInt8(size >= 256 ? 0 : size, 1); // height
    entry.writeUInt8(0, 2); // no palette
    entry.writeUInt8(0, 3); // reserved
    entry.writeUInt16LE(1, 4); // color planes
    entry.writeUInt16LE(32, 6); // bits per pixel
    entry.writeUInt32LE(buffer.length, 8);
    entry.writeUInt32LE(offset, 12);
    offset += buffer.length;
    entries.push(entry);
  }

  return Buffer.concat([header, ...entries, ...pngBuffers.map((p) => p.buffer)]);
}

async function main() {
  // favicon.ico — 16/32/48, round badge at each size (small sizes need
  // their own render, not a downscale of the 512, or the circle margin and
  // mark padding go proportionally wrong).
  const icoSizes = [16, 32, 48];
  const icoBuffers = await Promise.all(icoSizes.map(async (size) => ({ size, buffer: await roundBadge(size) })));
  writeFileSync(join(root, "src/app/favicon.ico"), packIco(icoBuffers));
  console.log("wrote src/app/favicon.ico");

  const icon512 = await roundBadge(512);
  writeFileSync(join(root, "src/app/icon.png"), icon512);
  writeFileSync(join(root, "public/icons/icon-512.png"), icon512);
  console.log("wrote src/app/icon.png, public/icons/icon-512.png");

  writeFileSync(join(root, "public/icons/icon-192.png"), await roundBadge(192));
  console.log("wrote public/icons/icon-192.png");

  writeFileSync(join(root, "src/app/apple-icon.png"), await solidSquare(180, 0.6));
  console.log("wrote src/app/apple-icon.png");

  // Safe zone is a circle of radius 40% of the icon size (205px at 512).
  // Scaling the mark to 65% of that diameter (0.65 * 0.8 = 0.52 of the full
  // canvas) leaves visible breathing room inside the safe zone rather than
  // just touching it.
  writeFileSync(join(root, "public/icons/icon-maskable-512.png"), await solidSquare(512, 0.52));
  console.log("wrote public/icons/icon-maskable-512.png");
}

await main();
